### ISSUE TITLE
VSCCValidateTx for transaction txId returned error: VSCC error: endorsement

### ISSUE THREAD

**Issue by AnswerAIL** [AnswerAIL/fabric-sdk-server#1]
> peer节点日志报错： VSCCValidateTx for transaction txId returned error: VSCC error: endorsement

解决方案： 背书策略中的 peer 需要改为 member
```yaml
user1: {"role": {"name": "peer ", "mspId": "Org1MSP"}}
# 修改为以下内容
user1: {"role": {"name": "member", "mspId": "Org1MSP"}}
```
`fabric 每个版本可能对应的背书策略会有所不同， 请参考官方源码对应的背书策略进行编辑`

 - [x] [fabric 1.3 背书策略模板](https://github.com/hyperledger/fabric-sdk-java/blob/release-1.3/src/test/fixture/sdkintegration/chaincodeendorsementpolicy.yaml)
